### PR TITLE
feature(Gradle): Gradle initial build test

### PR DESCRIPTION
**Pull request by heliocastro**
[//]: # (Copyright BMW CarIT GmbH 2022)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

- Build entire aplication with tests ( as long has couchdb set )
- Implement dependency versioning in a single place: gradle/libs.versions.toml
- Disable backend/utils and libraries log4j_support as not needed anymore

Signed-off-by: Helio Chissini de Castro <helio.chissini-de-castro@bmw.de>

### Suggest Reviewer
@mcjaeger 

### How To Test?
```./gradlew build --exclude-task test```

### CODE REVIEW

**Comment by mcjaeger** [comment]
so from a testing point of view, just two notices:
* gradle warpper is not there, needs to be installed first and then bootstrapped with "gradle wrapper"
* installation of thrift required (of course).

Good news:
* can compile with thrift 0.16 (if it runs then is another question)
* result is
```
BUILD SUCCESSFUL in 2m 24s
96 actionable tasks: 87 executed, 9 up-to-date
```
(tested with openjdk 11 on macos12.2)

**Comment by KoukiHama** [comment]
I did test with [24219fc](https://github.com/eclipse/sw360/commit/24219fc12a5ec554a9314989517f59be980a7812)

(tested with openjdk 11 on ubuntu 20.04)
lsb_release -a

> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.4 LTS
> Release:        20.04
> Codename:       focal



gradle wrapper was  OK

> ubuntu@sw360-15test:~/sw360_gradle/sw360$ gradle wrapper
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> BUILD SUCCESSFUL in 2m 2s
> 10 actionable tasks: 10 executed
> 

 ./gradlew build --exclude-task test was  also OK

> ubuntu@sw360:~/sw360_gradle/sw360$ ./gradlew build --exclude-task test
> Downloading https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
> ...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%
> 
> 
> BUILD SUCCESSFUL in 6m 25s
> 96 actionable tasks: 87 executed, 9 up-to-date
>

**Comment by mcjaeger** [comment]
I have compilation errors:
```
> Task :resource-server:compileJava
/Users/Shared/2bdelsw360/sw360/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java:74: warning: Field 'log' already exists
@Slf4j
^
/Users/Shared/2bdelsw360/sw360/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/changelog/ChangeLogController.java:110: warning: unreachable catch claus
                    } catch (IOException e) {
                      ^
  thrown type JsonProcessingException has already been caught
```
and:
```
> Task :datahandler:compileJava
/Users/Shared/2bdelsw360/sw360/libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseRepository.java:94: warning: non-varargs call of varargs method with inexact argument type for last parameter;
        ViewQuery query = createQuery(queryName).key(ComplexKey.of(keys));
                                                                   ^
  cast to Object for a varargs call
```
is it rebase is not OK or I have wrong dependencies (thrift?)

**Comment by heliocastro** [comment]
@mcjaeger  This are Warnings, not errors, and i think we should take a look on meeting today.

I'm overhauling lots of the the parts to get tests properly working ( including bnd process )
So, i think for now, what will work properly is:

```./gradlew clean build --exclude-task tests```

Don't forget to do a ```git pull --rebase``` or a clean tree before ( lots of force push on the branch )

If you want to build tests to see where is failing, will fail with some undefined reference that i didn't get it yet the logical part.


```org.eclipse.sw360.attachments.AttachmentHandlerTest > testAttachmentUsageCountWithFilter FAILED
java.lang.NoClassDefFoundError at AttachmentHandlerTest.java:54
Caused by: java.lang.ClassNotFoundException at AttachmentHandlerTest.java:54
java.lang.NoClassDefFoundError at AttachmentHandlerTest.java:67
Caused by: java.lang.ClassNotFoundException at AttachmentHandlerTest.java:67 
```

**Comment by mcjaeger** [comment]
> @mcjaeger This are Warnings, not errors, and i think we should take a look on meeting today.

I am sorry, you re right, warnings, not errors.

**Comment by heliocastro** [comment]
Drop
